/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoice Management API
 * API for managing invoices, users, and payments.
 * OpenAPI spec version: 1.0.0
 */

export type GetHealth200 = {
  status?: string;
};
