/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoice Management API
 * API for managing invoices, users, and payments.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetHealth200,
  UserDTO
} from '.././dto';




  /**
 * @summary Health check
 */
export const getHealth = <TData = AxiosResponse<GetHealth200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/health`,options
    );
  }
/**
 * @summary List users
 */
export const getUsers = <TData = AxiosResponse<UserDTO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/users`,options
    );
  }
