/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoice Management API
 * API for managing invoices, users, and payments.
 * OpenAPI spec version: 1.0.0
 */

export type UserDTORole = typeof UserDTORole[keyof typeof UserDTORole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDTORole = {
  ADMIN: 'ADMIN',
  USER: 'USER',
} as const;
